
local placeMaps = {
	["Limsa Lominsa - Upper Decks"] = 128,
	["Limsa Lominsa - Lower Decks"] = 129,
}

local zones = {
	
	
	[128] = { -- Limsa Lominsa - Upper Decks
		["name"] = "Limsa Lominsa - Upper Decks",
		["cont"] = "La Noscea",
		["climate"] = {
			["type"] = "coastal",
			["temp"] = "coastal",
			["humidity"] = "med",
			["nighthot"] = 0.67, -- percentage
			["nightcold"] = 1.27,
		},
		["effects"] = {
			["wet"] = 0.15,
			["tired"] = -0.2,
			["tense"] = -0.25,
			["uncomfortable"] = -0.5,
			["happy"] = 0.25,
			["flirty"] = 0.5,
			["amused"] = 0.2,
			["social"] = 1.0,
			["anxious"] = -0.1,
			["aetheric"] = 0.09,
		}
	},
	[129] = { -- Limsa Lominsa - Lower Decks
		["name"] = "Limsa Lominsa - Lower Decks",
		["cont"] = "La Noscea",
		["climate"] = {
			["type"] = "coastal",
			["temp"] = "coastal",
			["humidity"] = "med",
			["nighthot"] = 0.67, -- percentage
			["nightcold"] = 1.27,
		},
		["effects"] = {
			["wet"] = 0.15,
			["tired"] = -0.2,
			["tense"] = -0.25,
			["uncomfortable"] = -0.5,
			["happy"] = 0.25,
			["flirty"] = 0.5,
			["amused"] = 0.2,
			["social"] = 1.25,
			["anxious"] = -0.1,
			["aetheric"] = 0.17,
		}
	},
	[130] = { -- Ul'dah - Steps of Nald
		["name"] = "Ul'dah - Steps of Nald",
		["cont"] = "Thanalan",
		["climate"] = {
			["temp"] = "warm",
			["humidity"] = "low",
		},
		["effects"] = {
			["hot"] = 1.25,
			["cold"] = -5,
			["wet"] = -1.25,
			["tired"] = 0.15,
			["confident"] = 0.25,
			["uncomfortable"] = -0.15,
			["happy"] = 0.25,
			["flirty"] = 0.75,
			["playful"] = 0.5,
			["social"] = 1.35,
			["focused"] = 0.75,
			["aetheric"] = -0.13,
		}
	},
	[131] = {
		["name"] = "Ul'dah - Steps of Thal",
		["cont"] = "Thanalan",
		["climate"] = {
			["temp"] = "warm",
			["humidity"] = "med",
		},
		["effects"] = {
			["hot"] = 1.45,
			["cold"] = -5.65,
			["wet"] = -1.25,
			["tired"] = 0.15,
			["confident"] = 0.25,
			["uncomfortable"] = -0.15,
			["happy"] = 0.25,
			["flirty"] = 0.75,
			["playful"] = 0.5,
			["social"] = 0.95,
			["focused"] = 1.25,
			["aetheric"] = -0.13,
		}
	},
	[132] = {--New Gridania
		["name"] = "New Gridania",
		["cont"] = "The Black Shroud",
		["climate"] = {
			["type"] = "sylvan",
			["temp"] = "moderate",
			["humidity"] = "med",
			["nighthot"] = 1.17, -- percentage
			["nightcold"] = 1.77,
		},
		["effects"] = {
			["hot"] = 1.35,
			["cold"] = -3.5,
			["wet"] = 0.25,
			["tired"] = -0.25,
			["tense"] = -0.15,
			["uncomfortable"] = -0.15,
			["happy"] = 0.35,
			["curious"] = 0.35,
			["confident"] = 0.35,
			["amused"] = 0.35,
			["social"] = 0.75,
			["impatient"] = -0.25,
			["anxious"] = -0.1,
			["aetheric"] = 1.31,
		}
	},
	[133] = {--Old Gridania
		["name"] = "Old Gridania",
		["cont"] = "The Black Shroud",
		["climate"] = {
			["type"] = "sylvan",
			["temp"] = "moderate",
			["humidity"] = "med",
			["nighthot"] = 1.17, -- percentage
			["nightcold"] = 1.77,
		},
		["effects"] = {
			["hot"] = 1.25,
			["cold"] = -3.5,
			["wet"] = 0.25,
			["tired"] = -0.25,
			["tense"] = -0.15,
			["uncomfortable"] = -0.15,
			["happy"] = 0.35,
			["curious"] = 0.35,
			["confident"] = 0.35,
			["amused"] = 0.35,
			["social"] = 0.75,
			["impatient"] = -0.25,
			["anxious"] = -0.1,
			["aetheric"] = 1.37,
		}
	},
	[134] = {--Middle La Noscea
		["name"] = "Middle La Noscea",
		["cont"] = "La Noscea",
		["climate"] = {
			["type"] = "coastal",
			["temp"] = "coastal",
			["humidity"] = "med",
			["nighthot"] = 0.67, -- percentage
			["nightcold"] = 1.27,
		},
		["effects"] = {
			["hot"] = 0.35,
			["cold"] = -1.44,
			["wet"] = -1.15,
			["tired"] = 0.15,
			["confident"] = 0.25,
			["uncomfortable"] = -0.15,
			["happy"] = 0.25,
			["flirty"] = 0.75,
			["playful"] = 0.5,
			["social"] = -0.35,
			["focused"] = -0.15,
		}
	},
	[135] = {
		["name"] = "Lower La Noscea",
		["cont"] = "La Noscea",
		["climate"] = {
			["temp"] = "warm",
			["humidity"] = "med",
		},
		["effects"] = {
			["hot"] = 0.55,
			["cold"] = -2.5,
			["wet"] = 0.15,
			["tired"] = -0.2,
			["tense"] = -0.25,
			["uncomfortable"] = -0.5,
			["happy"] = 0.15,
			["amused"] = 0.15,
			["playful"] = 0.2,
			["social"] = -0.35,
			["anxious"] = -0.1,
		}
	},
	[144] = {
		["name"] = "The Gold Saucer",
		["cont"] = "Thanalan",
		["climate"] = {
			["temp"] = "normal",
			["humidity"] = "low",
		},
		["effects"] = {
			["hot"] = -1.37,
			["cold"] = 0.77,
			["wet"] = -1.15,
			["tired"] = 0.15,
			["confident"] = 0.25,
			["uncomfortable"] = -0.15,
			["happy"] = 0.25,
			["flirty"] = 0.75,
			["playful"] = 0.5,
			["social"] = -0.35,
			["focused"] = -0.15,
		}
	},
	[146] = {--Southern Thanalan - Sagoli Desert
		["name"] = "Southern Thanalan - Sagoli Desert",
		["cont"] = "Thanalan",
		["climate"] = {
			["type"] = "desert",
			["temp"] = "hot",
			["humidity"] = "very-low",
			["nighthot"] = 0.77, -- percentage
			["nightcold"] = 1.37,
		},
		["effects"] = {
			["hot"] = 0.13,
			["cold"] = -0.19,
			["wet"] = -1.15,
			["uncomfortable"] = -0.35,
			["dazed"] = 0.25,
			["disturbed"] = 0.25,
			["amused"] = -0.15,
			["curious"] = 0.15,
			["mischievous"] = 0.15,
			["angry"] = 0.15,
			["aetheric"] = 0.67,
		},
		["nighthot"] = -0.27,
		["nightcold"] = 0.37,
	},
	[147] = {
		["name"] = "Northern Thanalan",
		["cont"] = "Thanalan",
		["effects"] = {
			["hot"] = 0.13,
			["cold"] = -0.19,
			["wet"] = -1.15,
			["tired"] = -0.15,
			["confident"] = 0.45,
			["uncomfortable"] = -0.35,
			["happy"] = 0.45,
			["social"] = 1.95,
			["dazed"] = 0.25,
			["flippant"] = 0.25,
			["amused"] = -0.15,
			["curious"] = 0.15,
			["mischievous"] = 0.15,
			["angry"] = 0.15,
			["tense"] = 0.35,
			["aetheric"] = 0.67,
		},
		["nighthot"] = -0.27,
		["nightcold"] = 0.37,
	},
	[153] = {
		["name"] = "South Shroud",
		["cont"] = "The Black Shroud",
		["effects"] = {
			["hot"] = 0.75,
			["cold"] = -1.5,
			["wet"] = -0.25,
			["tired"] = -0.15,
			["tense"] = -0.25,
			["uncomfortable"] = -0.25,
			["nosey"] = 0.17,
			["curious"] = 0.17,
			["impatient"] = -0.17,
			["anxious"] = -0.15,
			["playful"] = 0.15,
			["energized"] = -0.13,
			["aetheric"] = -0.17,
		}
	},
	[154] = {
		["name"] = "North Shroud",
		["cont"] = "The Black Shroud",
		["effects"] = {
			["hot"] = 0.45,
			["cold"] = -0.66,
			["wet"] = -0.25,
			["tired"] = -0.15,
			["tense"] = -0.25,
			["uncomfortable"] = -0.25,
			["nosey"] = 0.17,
			["curious"] = 0.17,
			["impatient"] = -0.17,
			["anxious"] = -0.15,
			["playful"] = 0.15,
			["energized"] = -0.07,
			["aetheric"] = 0.17,
		}
	},
	[156] = {
		["name"] = "Mor Dhona",
		["cont"] = "Mor Dhona",
		["effects"] = {
			["hot"] = 0.23,
			["cold"] = -0.31,
			["wet"] = -1.15,
			["tired"] = -0.15,
			["confident"] = 0.45,
			["uncomfortable"] = -0.35,
			["happy"] = 0.45,
			["social"] = 1.95,
			["dazed"] = 0.25,
			["flippant"] = 0.25,
			["amused"] = -0.15,
			["curious"] = 0.15,
			["mischievous"] = 0.15,
			["angry"] = 0.15,
			["tense"] = 0.35,
			["aetheric"] = 0.99,
		},
		["nighthot"] = -0.37,
		["nightcold"] = 0.43,
	},
	[177] = { -- Limsa Lominsa - Mizzenmast Inn
		["name"] = "Mizzenmast Inn",
		["cont"] = "La Noscea",
		["climate"] = {
			["type"] = "indoors",
			["temp"] = "indoors-moderate",
			["humidity"] = "med",
			["nighthot"] = 0.67, -- percentage
			["nightcold"] = 1.27,
		},
		["effects"] = {
			["wet"] = -0.15,
			["tired"] = -1.2,
			["tense"] = -1.25,
			["uncomfortable"] = -1.5,
			["happy"] = 0.25,
			["sleepy"] = -3.6,
			["amused"] = 0.2,
			["energized"] = 0.3,
			["anxious"] = -0.1,
			["aetheric"] = -1.77,
		}
	},
	[250] = {
		["name"] = "Wolves' Den Pier",
		["cont"] = "La Noscea",
	},
	[339] = { --MIST
		["name"] = "Mist",
		["cont"] = "La Noscea",
		["climate"] = {
			["type"] = "coastal",
			["temp"] = "coastal",
			["humidity"] = "med",
			["nighthot"] = 0.67, -- percentage
			["nightcold"] = 1.27,
		},
		["effects"] = {
			["wet"] = 0.15,
			["refreshed"] = 0.23,
			["tense"] = -0.25,
			["uncomfortable"] = -0.5,
			["happy"] = 0.25,
			["flirty"] = 0.5,
			["amused"] = 0.2,
			["social"] = 0.1,
			["anxious"] = -0.1,
		},
	},
	[384] = { --Private Chambers - Mist
		["name"] = "Private Chambers - Mist",
		["cont"] = "La Noscea",
		["climate"] = {
			["type"] = "indoors",
			["temp"] = "indoors",
			["humidity"] = "low",
			["nighthot"] = 0.67, -- percentage
			["nightcold"] = 1.27,
		},
		["effects"] = {
			["refreshed"] = 0.23,
			["sleepy"] = -2.7,
		},
	},
	[392] = {
		["name"] = "Sanctum of the Twelve",
		["cont"] = "Black Shroud",
		["effects"] = {
			["hot"] = 0.55,
			["cold"] = -3,
			["wet"] = 0.15,
			["tired"] = -0.2,
			["tense"] = -0.25,
			["uncomfortable"] = -0.5,
			["happy"] = 0.25,
			["flirty"] = 0.5,
			["amused"] = 0.2,
			["social"] = 0.1,
			["anxious"] = -0.1,
			["aetheric"] = 7.77,
		},
	},
	
	[418] = {
		["name"] = "Foundation",
		["cont"] = "Coerthas",
		["effects"] = {
			["hot"] = -2.79,
			["cold"] = 3.12,
			["wet"] = -0.45,
			["tired"] = -0.15,
			["tense"] = 0.15,
			["uncomfortable"] = 0.35,
		},
		["nighthot"] = -3.75,
		["nightcold"] = 4.32,
	},
	[536] = { --Maelstrom Barracks
		["name"] = "Maelstrom Barracks",
		["cont"] = "La Noscea",
		["climate"] = {
			["type"] = "coastal",
			["temp"] = "coastal",
			["humidity"] = "med",
			["nighthot"] = 0.67, -- percentage
			["nightcold"] = 1.27,
		},
		["effects"] = {
			["wet"] = 0.15,
			["refreshed"] = 0.23,
			["amused"] = 0.2,
			["social"] = 0.3,
			["sleepy"] = -1.7,
		},
	},
	[561] = {
		["name"] = "Palace of the Dead",
		["cont"] = "Black Shroud",
		["effects"] = {
			["hot"] = 1.15,
			["cold"] = -2.5,
			["wet"] = 0.25,
			["tired"] = -0.15,
			["tense"] = -0.25,
			["uncomfortable"] = -0.25,
			["happy"] = 0.25,
			["curious"] = 0.25,
			["confident"] = 0.15,
			["impatient"] = -0.35,
			["anxious"] = -0.15,
			["aetheric"] = -0.55,
		},
	},
	[613] = {
		["name"] = "Ruby Sea",
		["cont"] = "Othard",
		["effects"] = {
			["hot"] = 1.15,
			["cold"] = -2.5,
			["wet"] = 0.25,
			["tired"] = -0.15,
			["tense"] = -0.25,
			["uncomfortable"] = -0.25,
			["happy"] = 0.25,
			["curious"] = 0.25,
			["confident"] = 0.15,
			["impatient"] = -0.35,
			["anxious"] = -0.15,
			["playful"] = 0.15,
		}
	},
	[816] = {
		["name"] = "Il Mheg",
		["cont"] = "Norvrandt",
		["effects"] = {
			["hot"] = 0.15,
			["cold"] = -0.5,
			["wet"] = -0.15,
			["tired"] = -0.25,
			["amused"] = 0.45,
			["mischievous"] = 0.85,
			["happy"] = 0.15,
			["curious"] = 0.95,
			["confident"] = 0.20,
			["embarrassed"] = 0.35,
			["anxious"] = 0.15,
			["playful"] = 0.75,
			["puzzled"] = 0.15,
			["surprised"] = 0.65,
			["focused"] = -0.15,
			["dazed"] = 0.15,
			["bored"] = -0.25,
			["flippant"] = 0.25,
		}
	},
	[813] = {
		["name"] = "Lakeland",
		["cont"] = "Norvrandt",
		["effects"] = {
			["hot"] = 0.05,
			["cold"] = -0.15,
			["wet"] = -0.35,
			["tired"] = -0.25,
			["amused"] = 0.55,
			["curious"] = 0.25,
			["confident"] = 0.10,
			["playful"] = 0.15,
			["puzzled"] = 0.25,
			["surprised"] = 0.35,
			["focused"] = 0.15,
			["dazed"] = 0.10,
		}
	},
	[815] = {
		["name"] = "Amh Araeng",
		["cont"] = "Norvrandt",
		["effects"] = {
			["hot"] = 0.65,
			["cold"] = -0.65,
			["wet"] = -0.55,
			["tired"] = -0.25,
			["amused"] = 0.55,
			["curious"] = 0.25,
			["confident"] = 0.10,
			["playful"] = 0.15,
			["puzzled"] = 0.25,
			["surprised"] = 0.35,
			["focused"] = 0.15,
			["dazed"] = 0.10,
		}
	},
	[832] = {
		["name"] = "Air Force One",
		["cont"] = "Gold Saucer",
		["effects"] = {
			["hot"] = -0.35,
			["cold"] = 0.27,
			["wet"] = -1.15,
			["tired"] = 0.15,
			["confident"] = 0.35,
			["energized"] = -0.95,
			["happy"] = 0.25,
			["flirty"] = -0.15,
			["playful"] = 0.65,
			["social"] = -0.35,
			["focused"] = -0.45,
			["aetheric"] = -0.75,
		}
	},
	[956] = {
		["name"] = "Labyrinthos",
		["cont"] = "The Northern Empty",
	},
	[957] = {
		["name"] = "Thavnair",
		["cont"] = "Ilsabard",
		["effects"] = {
			["hot"] = 2.55,
			["cold"] = -2.5,
			["wet"] = 0.35,
			["tired"] = -0.15,
			["tense"] = -0.25,
			["uncomfortable"] = -0.25,
			["happy"] = 0.15,
			["curious"] = 0.15,
			["bored"] = -0.15,
			["playful"] = 0.15,
		}
	},
	[958] = {--Garlemald
		["name"] = "Garlemald",
		["cont"] = "Ilsabard",
		["climate"] = {
			["type"] = "tundra",
			["temp"] = "tundra",
			["humidity"] = "low",
			["nighthot"] = 0.41, -- percentage
			["nightcold"] = 1.71,
		},
		["effects"] = {
			["hot"] = -2.15,
			["cold"] = 2.25,
			["wet"] = 0.15,
			["focused"] = -0.25,
			["tense"] = 0.15,
			["nosey"] = -0.15,
			["uncomfortable"] = 0.25,
			["happy"] = -0.15,
			["curious"] = -0.35,
			["bored"] = 0.25,
			["mischievous"] = -0.15,
			["confident"] = -0.25,
			["flippant"] = -0.25,
		}
	},
	[959] = {
		["name"] = "Mare Lamentorum",
		["cont"] = "The Sea of Stars",
		["effects"] = {
			["hot"] = 3.15,
			["cold"] = -3.25,
			["wet"] = -1.95,
			["focused"] = 0.25,
			["tense"] = 0.15,
			["nosey"] = 0.45,
			["uncomfortable"] = 0.15,
			["happy"] = 0.15,
			["curious"] = 0.75,
			["bored"] = -0.25,
			["mischievous"] = 0.15,
			["confident"] = 0.25,
			["flippant"] = -0.25,
		},
		["nighthot"] = -4.25,
		["nightcold"] = 3.65,
	},
	[962] = {
		["name"] = "Old Sharlayan",
		["cont"] = "The Northern Empty",
		["climate"] = {
			["type"] = "coastal",
			["temp"] = "cool",
			["humidity"] = "moderate",
			["nighthot"] = 0.91, -- percentage
			["nightcold"] = 1.11,
		},
		["optimal"] = 9.33,
		["effects"] = {
			["wet"] = 0.15,
			["focused"] = 0.45,
			["tense"] = -0.35,
			["nosey"] = 0.25,
			["uncomfortable"] = -0.25,
			["happy"] = 0.15,
			["curious"] = 0.35,
			["bored"] = -0.25,
			["mischievous"] = 0.15,
			["confident"] = 0.25,
		}
	},
	[963] = {
		["name"] = "Radz-at-Han",
		["cont"] = "Ilsabard",
		["effects"] = {
			["hot"] = 2.75,
			["cold"] = -2.25,
			["wet"] = 0.55,
			["tired"] = 0.15,
			["social"] = 0.35,
			["uncomfortable"] = 0.15,
			["amused"] = 0.15,
			["curious"] = 0.25,
			["bored"] = -0.15,
			["mischievous"] = 0.25,
		}
	},
	[990] = {
		["name"] = "Andron",
		["cont"] = "The Northern Empty",
		["effects"] = {
			["hot"] = 0.45,
			["cold"] = -0.25,
			["wet"] = 0.15,
			["focused"] = 0.45,
			["tense"] = -0.35,
			["nosey"] = 0.25,
			["uncomfortable"] = -0.25,
			["happy"] = 0.15,
			["curious"] = 0.35,
			["bored"] = -0.25,
			["mischievous"] = 0.15,
			["confident"] = 0.25,
		}
	},
	[1055] = {
		["name"] = "????",
		["cont"] = "Unnamed Island",
		["effects"] = {
			["hot"] = 0.31,
			["cold"] = -4.39,
			["wet"] = 0.21,
			["tired"] = -0.11,
			["sleepy"] = -0.11,
			["confident"] = 0.11,
			["social"] = -1.21,
			["dazed"] = -0.11,
			["amused"] = -0.21,
			["curious"] = 0.21,
			["angry"] = 0.369,
			["tense"] = 0.369,
			["aetheric"] = 0.23,
		},
		["nighthot"] = -0.75,
		["nightcold"] = 0.65,
	},
	[1061] = {
		["name"] = "????",
		["cont"] = "The Omphalos",
		["effects"] = {
			["hot"] = -7.77,
			["cold"] = -7.77,
			["wet"] = -7.77,
			["tired"] = -7.77,
			["sleepy"] = -7.77,
			["confident"] = 0.11,
			["uncomfortable"] = -7.77,
			["happy"] = 0.11,
			["social"] = -7.77,
			["dazed"] = 0.369,
			["flippant"] = -7.77,
			["amused"] = -7.77,
			["curious"] = 0.11,
			["amazed"] = 0.11,
			["mischievous"] = -7.77,
			["angry"] = -0.369,
			["tense"] = -0.369,
			["aetheric"] = -3.93,
		},
	},
	[1098] = {
		["name"] = "Sylphstep",
		["cont"] = "The Black Shroud", -- Leap of Faith
		["effects"] = {
			["hot"] = 0.75,
			["cold"] = -1.5,
			["playful"] = -0.25,
			["tired"] = 0.25,
			["tense"] = 0.25,
			["uncomfortable"] = -0.25,
			["nosey"] = 0.27,
			["curious"] = 0.27,
			["impatient"] = -0.27,
			["anxious"] = 0.15,
			["amused"] = 0.15,
			["energized"] = -0.27,
			["aetheric"] = 0.37,
		}
	},
	
	[1185] = {--Tuliyollal
		["name"] = "Tuliyollal",
		["cont"] = "Yok Tural",
		["climate"] = {
			["type"] = "coastal",
			["temp"] = "coastal",
			["humidity"] = "high",
			["nighthot"] = 0.61, -- percentage
			["nightcold"] = 1.61,
		},
		["effects"] = {
			["wet"] = 1.17,
			["tired"] = -0.15,
			["confident"] = 0.15,
			["uncomfortable"] = -0.15,
			["happy"] = 0.15,
			["curious"] = 0.25,
			["playful"] = 0.15,
			["social"] = 0.65,
			["focused"] = 0.15,
		}
	},
	[1186] = {
		["name"] = "Solution Nine",
		["cont"] = "Xak Tural",
		["effects"] = {
			["hot"] = -1.75,
			["cold"] = -1.75,
			["wet"] = -0.45,
			["tired"] = -0.25,
			["confident"] = 0.65,
			["uncomfortable"] = -0.25,
			["happy"] = 0.45,
			["curious"] = 0.95,
			["playful"] = 0.85,
			["sleepy"] = -0.41,
			["social"] = 0.65,
			["focused"] = 0.75,
			["amused"] = 0.85,
			["aetheric"] = 0.37,
		}
	},
	[1187] = {
		["name"] = "Urqopacha",
		["cont"] = "Yok Tural",
		["effects"] = {
			["hot"] = 0.65,
			["cold"] = -0.75,
			["wet"] = -0.45,
			["tired"] = -0.15,
			["confident"] = 0.15,
			["uncomfortable"] = -0.15,
			["happy"] = 0.15,
			["curious"] = 0.25,
			["playful"] = 0.15,
			["social"] = 0.15,
			["focused"] = 0.15,
		}
	},
	[1188] = {
		["name"] = "Kozama'uka",
		["cont"] = "Yok Tural",
		["effects"] = {
			["hot"] = 0.95,
			["cold"] = -0.95,
			["wet"] = -0.35,
			["tired"] = -0.15,
			["confident"] = 0.25,
			["uncomfortable"] = -0.15,
			["happy"] = 0.20,
			["curious"] = 0.25,
			["mischievous"] = 0.15,
			["social"] = 0.15,
			["focused"] = 0.15,
			["tense"] = -0.15,
		}
	},
	[1189] = {--Mamook
		["name"] = "The Ja Tiika Heartland",
		["cont"] = "Yak T'el",
		["climate"] = {
			["type"] = "enchantedforest",
			["temp"] = "enchantedforest",
			["humidity"] = "normal",
			["nighthot"] = 0.61, -- percentage
			["nightcold"] = 1.61,
		},
		["effects"] = {
			["wet"] = 0.10,
			["bored"] = -0.15,
			["confident"] = 0.25,
			["uncomfortable"] = -0.15,
			["happy"] = 0.20,
			["curious"] = 0.65,
			["mischievous"] = 0.25,
			["social"] = 0.15,
			["focused"] = 0.45,
			["tense"] = -0.25,
			["puzzled"] = 0.25,
			["mischievous"] = 0.35,
		}
	},
	[1190] = {--Shaaloani
		["name"] = "Shaaloani",
		["cont"] = "Xak Tural",
		["climate"] = {
			["type"] = "plains",
			["temp"] = "plains",
			["humidity"] = "low",
			["nighthot"] = 0.79, -- percentage
			["nightcold"] = 1.36,
		},
		["effects"] = {
			["wet"] = -1.75,
			["tired"] = -0.15,
			["confident"] = 0.35,
			["uncomfortable"] = -0.15,
			["responsible"] = 0.25,
			["happy"] = 0.35,
			["flirty"] = 0.25,
			["playful"] = 0.35,
			["nosey"] = 0.25,
			["social"] = 0.15,
			["focused"] = 0.15,
			["angry"] = 0.15,
			["amused"] = 0.15,
			["bored"] = 0.15,
		},
		--["nighthot"] = -0.25,
		--["nightcold"] = 0.65,
	},
	[1191] = {--Heritage Found
		["name"] = "Heritage Found",
		["cont"] = "Xak Tural",
		["climate"] = {
			["type"] = "umbralplains",
			["temp"] = "umbralplains",
			["humidity"] = "verylow",
			["nighthot"] = 0.69, -- percentage
			["nightcold"] = 1.63,
		},
		["effects"] = {
			["wet"] = -3.25,
			["tired"] = -0.15,
			["confident"] = -0.15,
			["uncomfortable"] = 0.25,
			["amazed"] = 0.25,
			["happy"] = -0.15,
			["flirty"] = -0.15,
			["playful"] = 0.15,
			["nosey"] = 0.35,
			["social"] = -0.45,
			["focused"] = -0.25,
			["angry"] = 0.65,
			["amused"] = -0.15,
			["bored"] = -0.15,
		},
		["nighthot"] = -0.45,
		["nightcold"] = 0.55,
	},
	[1237] = {
		["name"] = "Sinus Ardorum",
		["cont"] = "The Sea of Stars",
		["effects"] = {
			["hot"] = 3.15,
			["cold"] = -3.25,
			["wet"] = -1.95,
			["focused"] = 0.25,
			["tense"] = 0.15,
			["nosey"] = 0.45,
			["uncomfortable"] = 0.15,
			["happy"] = 0.15,
			["curious"] = 0.75,
			["bored"] = -0.25,
			["mischievous"] = 0.15,
			["confident"] = 0.25,
			["aetheric"] = 1.37,
		},
		["nighthot"] = -4.25,
		["nightcold"] = 3.65,
	},
	[1249] = {
		["name"] = "Private Cottage - Mist",
		["cont"] = "La Noscea",
		["climate"] = {
			["type"] = "indoors",
			["temp"] = "cool",
			["humidity"] = "low",
			["nighthot"] = 0.81, -- percentage
			["nightcold"] = 1.21,
		},
	},
	[1252] = {
		["name"] = "South Horn",
		["cont"] = "Occult Crescent",
		["climate"] = {
			["type"] = "enchanted-island",
			["temp"] = "enchanted-island",
			["humidity"] = "moderate",
			["nighthot"] = 0.66,
			["nightcold"] = 1.33,
		},
		["effects"] = {
			["wet"] = 0.31,
			["focused"] = -0.25,
			["playful"] = 0.45,
			["curious"] = 0.75,
			["bored"] = -0.25,
			["mischievous"] = 0.15,
			["confident"] = -0.15,
			["aetheric"] = -1.37,
		},
	},
	[1269] = {
		["name"] = "Phantom Village",
		["cont"] = "Occult Crescent",
		["climate"] = {
			["type"] = "coastal",
			["temp"] = "coastal",
			["humidity"] = "high",
			["nighthot"] = 0.77,
			["nightcold"] = 1.11,
		},
		["effects"] = {
			["wet"] = 0.35,
			["focused"] = 0.25,
			["nosey"] = 0.45,
			["curious"] = 0.75,
			["bored"] = -0.25,
			["mischievous"] = 0.15,
			["confident"] = 0.15,
			["aetheric"] = -1.37,
		},
		
	},
	[1278] = {
		["name"] = "Phantom Village",
		["cont"] = "Occult Crescent",
		["climate"] = {
			["type"] = "enchanted-island",
			["temp"] = "enchanted-island",
			["humidity"] = "moderate",
			["nighthot"] = 0.66,
			["nightcold"] = 1.33,
		},
		["effects"] = {
			["wet"] = 0.31,
			["focused"] = -0.25,
			["playful"] = 0.45,
			["curious"] = 0.75,
			["bored"] = -0.25,
			["mischievous"] = 0.15,
			["confident"] = -0.15,
			["aetheric"] = -1.37,
		},
		["nighthot"] = -1.45,
		["nightcold"] = 0.95,
	},

}



return {zones, placeMaps}